name: poppyn
channels:
  - defaults
dependencies:
  - _anaconda_depends=2023.09
  - abseil-cpp=20230802.0
  - aiobotocore=2.7.0
  - aiohttp=3.9.0
  - aioitertools=0.7.1
  - aiosignal=1.2.0
  - alabaster=0.7.12
  - anaconda=custom
  - anyio=3.5.0
  - aom=3.6.0
  - appdirs=1.4.4
  - applaunchservices=0.3.0
  - appnope=0.1.2
  - appscript=1.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - arrow-cpp=11.0.0
  - astroid=2.14.2
  - astropy=5.3.4
  - asttokens=2.0.5
  - async-lru=2.0.4
  - atomicwrites=1.4.0
  - attrs=23.1.0
  - automat=20.2.0
  - autopep8=1.6.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - babel=2.11.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.2
  - binaryornot=0.4.4
  - black=23.11.0
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.3
  - bokeh=3.3.0
  - boost-cpp=1.82.0
  - botocore=1.31.64
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.10.5
  - ca-certificates=2023.08.22
  - certifi=2023.11.17
  - cffi=1.16.0
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - colorcet=3.0.1
  - comm=0.1.2
  - constantly=15.1.0
  - contourpy=1.2.0
  - cookiecutter=2.5.0
  - cryptography=41.0.3
  - cssselect=1.1.0
  - curl=8.4.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cytoolz=0.12.0
  - dask=2023.11.0
  - dask-core=2023.11.0
  - datasets=2.12.0
  - datashader=0.16.0
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.6
  - distributed=2023.11.0
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - filelock=3.13.1
  - flake8=6.0.0
  - flask=2.2.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2023.10.0
  - gensim=4.3.0
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - greenlet=2.0.1
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtest=1.14.0
  - h5py=3.9.0
  - hdf5=1.12.1
  - heapdict=1.0.1
  - holoviews=1.18.1
  - huggingface_hub=0.17.3
  - hvplot=0.9.0
  - hyperlink=21.0.0
  - icu=73.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.31.4
  - imagesize=1.4.1
  - imbalanced-learn=0.11.0
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - incremental=21.3.0
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intake=0.6.8
  - intervaltree=3.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - isort=5.9.3
  - itemadapter=0.3.0
  - itemloaders=1.0.4
  - itsdangerous=2.0.1
  - jaraco.classes=3.2.1
  - jedi=0.18.1
  - jellyfish=1.0.1
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.2.0
  - jpeg=9e
  - jq=1.6
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.9
  - jxrlib=1.1
  - kaleido-core=0.2.1
  - keyring=23.13.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.6.0
  - lazy_loader=0.3
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.4.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzopfli=1.0.3
  - linkify-it-py=2.0.0
  - llvm-openmp=14.0.6
  - llvmlite=0.41.0
  - locket=1.0.0
  - lxml=4.9.3
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - mathjax=2.7.5
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - mistune=2.0.4
  - more-itertools=10.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - multidict=6.0.4
  - multipledispatch=0.6.0
  - multiprocess=0.70.14
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql=5.7.24
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nltk=3.8.1
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numba=0.58.1
  - numexpr=2.8.7
  - numpy=1.26.2
  - numpy-base=1.26.2
  - numpydoc=1.5.0
  - oniguruma=6.9.7.1
  - openjpeg=2.3.0
  - openpyxl=3.0.10
  - openssl=3.0.12
  - orc=1.7.4
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.1.1
  - pandocfilters=1.5.0
  - panel=1.3.1
  - param=2.0.1
  - parsel=1.6.0
  - parso=0.8.3
  - partd=1.4.1
  - pathspec=0.10.3
  - patsy=0.5.3
  - pcre=8.45
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=3.10.0
  - plotly=5.9.0
  - pluggy=1.0.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - protego=0.1.16
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pyarrow=11.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pyct=0.5.0
  - pycurl=7.45.2
  - pydispatcher=2.0.5
  - pydocstyle=6.3.0
  - pyerfa=2.0.0
  - pyflakes=3.0.1
  - pygments=2.15.1
  - pylint=2.16.2
  - pylint-venv=2.3.0
  - pyls-spyder=0.4.0
  - pyobjc-core=9.0
  - pyobjc-framework-cocoa=9.0
  - pyobjc-framework-coreservices=9.0
  - pyobjc-framework-fsevents=9.0
  - pyodbc=4.0.39
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - pytables=3.8.0
  - pytest=7.4.0
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-kaleido=0.2.1
  - python-lmdb=1.4.1
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.7.2
  - python-slugify=5.0.2
  - python-snappy=0.6.1
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python.app=3
  - pytoolconfig=1.2.5
  - pytz=2023.3.post1
  - pyviz_comms=2.3.0
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qdarkstyle=3.0.2
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.2.2
  - qtconsole=5.4.2
  - qtpy=2.4.1
  - queuelib=1.6.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - regex=2023.10.3
  - requests=2.31.0
  - requests-file=1.5.1
  - responses=0.13.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.3.5
  - rope=1.7.0
  - rpds-py=0.10.6
  - rtree=1.0.1
  - s3fs=2023.10.0
  - safetensors=0.4.0
  - scikit-image=0.20.0
  - scikit-learn=1.2.2
  - scipy=1.11.4
  - scrapy=2.8.0
  - seaborn=0.12.2
  - send2trash=1.8.2
  - service_identity=18.1.0
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.1.9
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.4.3
  - spyder-kernels=2.4.4
  - sqlalchemy=2.0.21
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - sympy=1.12
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tblib=1.7.0
  - tenacity=8.2.2
  - terminado=0.17.1
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2023.4.12
  - tinycss2=1.2.1
  - tk=8.6.12
  - tldextract=3.2.0
  - tokenizers=0.13.2
  - toml=0.10.2
  - tomlkit=0.11.1
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - transformers=4.32.1
  - twisted=22.10.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - uc-micro-py=1.0.1
  - ujson=5.4.0
  - unidecode=1.2.0
  - unixodbc=2.3.11
  - urllib3=1.26.18
  - utf8proc=2.6.1
  - w3lib=1.21.0
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - whatthepatch=1.0.2
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - wrapt=1.14.1
  - wurlitzer=3.0.2
  - xarray=2023.6.0
  - xlwings=0.29.1
  - xxhash=0.8.0
  - xyzservices=2022.9.0
  - xz=5.4.2
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.9.3
  - zeromq=4.3.4
  - zfp=1.0.0
  - zict=3.0.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zope=1.0
  - zope.interface=5.4.0
  - zstd=1.5.5
